version: "3.7"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
    - todo-mysql-data:/var/lib/mysql
    environment:
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
volumes:
  todo-mysql-data:
    external:
      name:
        todo-mysql-data
